### ISSUE TITLE
Add CCF as a Unit of Measurement

### ISSUE THREAD

**Issue by esmoyer** [cpyarger/Home-Assistant-Addons#17]
I have been working to rebuild a new HA instance and using this add-in rather than the MQTT one. My gas and water provider meters measure in CCF (centi cubic feet), would it be possible to add that as a measurement options for water and gas? I was looking at the code, but am not sure if I forked this, where I would add the option or calculation for this. (Sorry, not super great at Github or coding stuff yet; have just dabbled)

**Describe the solution you'd like**
Be able to select CCF for unit of measurement for Water and Gas

**Describe alternatives you've considered**
I have done the calculation in YAML templates with the MQTT SDR add-in, which works, but would like it to just have the measurement straight from the source. Water would be simple, just diving by 100 to go from ft3 to CCF. But Gas would be different; I know HomeAssistant needs m3 for the dashboard so right now I have a YAML template to convert the CCF to m3, so wouldn't be sure how to handle that within the add-in itself.

Not a huge deal, just figured I'd check. Thanks!

**Comment by esmoyer** [comment]
Ran into an issue using my sensor YAML templates with this as when HA restarts, the sensors go to unknown or 0 until the add-in gets a new update but then it adds that entire amount to the template sensor, so if my water reading is 150, after a restart it will be 300 and again 450 adding whatever the reading was to the previous amount. Not sure how to retain the value through restarts.

**Comment by pasyn** [comment]
To clarify, you need the addon to read the meter in CCF and then output in ft^3 for water and m^3 for gas

**Comment by pasyn** [comment]
I am working on some changes that will allow you to set a multiplier for each utility. For example, setting the multiplier to 2.83 should convert the CCF read from the meter to m^3. Then select m^3 as your output unit.

**Comment by esmoyer** [comment]
Awesome, appreciate it and excited to try it out!

**Comment by pasyn** [comment]
@esmoyer I have an update for you to test. Add the following repository to HA and install the SDRMR-TESTING add-on.

`https://github.com/pasyn/Home-Assistant-Addons`

Let me know if it works as expected and solves the issue or if you run into any bugs.

**Comment by esmoyer** [comment]
Nice! I got it installed and seems to be working well. I will need to do some testing to see if it retains the values through restarts and isn't resetting to 0 then jumping up. 

I'll still have to re-figure out how I want to handle the HA energy dashboard wanting gas to be in m^3 but my meter outputs and the utility charges by CCF (so being able to use that same value to estimate costs in a calculation). I also need to see how the water does since I can only choose gal or L for units in the add-on but it's actually coming in as CCF from the meter.

I'll keep at it. Thanks for the great work!

**Comment by pasyn** [comment]
The gallons or liters are the output units. That is what the addon appends to the number when passing it to HA. Set the multiplier to convert your input units (from the meter) to match the appropriate output unit. For example CCF*2.83=m^3 or CCF*748.1=gal.

I don't have a way to make the dashboard work with CCF but you can convert the per CCF price to a per Gal price so that the energy dashboard reports the correct measurements in gallons as well as the correct cost based on usage.

The state values will always revert to 0 after a reboot. That is a limitation of home assistant add-ons and there is nothing we can do about it. But it should not affect your calculations on the dashboard as the meter value will be restored shortly after reboot. On the energy dashboard graph, you may see an hour of no usage and then the next hour will be the combined usage for both hours. That is the worst of it. Day to day usage should be unaffected by the reboot.
